"""Added sets

Revision ID: 0408d1188736
Revises: 4ed76c4b6e6a
Create Date: 2024-10-26 12:11:02.531523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0408d1188736'
down_revision: Union[str, None] = '4ed76c4b6e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_name')
    )
    op.create_table('set_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'product_id', name='uix_set_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_items')
    op.drop_table('sets')
    # ### end Alembic commands ###
