"""Deleted additional details column from products

Revision ID: 1816a78ab9ac
Revises: a59a2db154a3
Create Date: 2024-10-18 18:20:51.087405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1816a78ab9ac'
down_revision: Union[str, None] = 'a59a2db154a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'additional_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
