"""Modified personalisation

Revision ID: 262ef1bd281c
Revises: 93a3f2b4b214
Create Date: 2025-01-03 01:11:25.156453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262ef1bd281c'
down_revision: Union[str, None] = '93a3f2b4b214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('personalization', sa.JSON(), nullable=True))
    op.drop_column('carts', 'personalised_size')
    op.drop_column('carts', 'personalised_name')
    op.drop_column('carts', 'personalised_date')
    op.drop_column('carts', 'personalised_member')
    op.drop_column('carts', 'personalised_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('personalised_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('personalised_member', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('personalised_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('personalised_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('personalised_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carts', 'personalization')
    # ### end Alembic commands ###
