"""Revamped product database

Revision ID: 2e07013f2b73
Revises: 626159cf2083
Create Date: 2024-10-15 18:02:53.594956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e07013f2b73'
down_revision: Union[str, None] = '626159cf2083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trousseaus')
    op.add_column('products', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    op.create_table('trousseaus',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dimensions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('child_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('custom_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('custom_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], name='trousseaus_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trousseaus_pkey')
    )
    # ### end Alembic commands ###
