"""Added product name to cart

Revision ID: 3758f347c579
Revises: dc3240411291
Create Date: 2024-12-06 02:51:26.414650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3758f347c579'
down_revision: Union[str, None] = 'dc3240411291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'product_name')
    # ### end Alembic commands ###
