"""Reset personalizations

Revision ID: 4846713e6d02
Revises: 262ef1bd281c
Create Date: 2025-01-03 01:34:33.421070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4846713e6d02'
down_revision: Union[str, None] = '262ef1bd281c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('personalised_name', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_date', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_message', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_size', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_member', sa.String(), nullable=True))
    op.drop_column('carts', 'personalization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('personalization', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('carts', 'personalised_member')
    op.drop_column('carts', 'personalised_size')
    op.drop_column('carts', 'personalised_message')
    op.drop_column('carts', 'personalised_date')
    op.drop_column('carts', 'personalised_name')
    # ### end Alembic commands ###
