"""Made categories from JSON to List

Revision ID: 4ed76c4b6e6a
Revises: 58b43ef9c580
Create Date: 2024-10-21 21:42:53.238283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed76c4b6e6a'
down_revision: Union[str, None] = '58b43ef9c580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.execute('ALTER TABLE products ALTER COLUMN categories TYPE VARCHAR[] USING ARRAY[categories]::VARCHAR[]')

        op.execute('ALTER TABLE products ALTER COLUMN secondary_images TYPE VARCHAR[] USING ARRAY[secondary_images]::VARCHAR[]')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'secondary_images',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'categories',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
