"""Changed carts

Revision ID: 53e97237d32e
Revises: 30e69d9415c1
Create Date: 2024-11-16 13:39:58.375607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e97237d32e'
down_revision: Union[str, None] = '30e69d9415c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('personalised_name', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_date', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_message', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_size', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('personalised_member', sa.String(), nullable=True))
    op.drop_constraint('uix_user_product_cart', 'carts', type_='unique')
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'products', ['product_id'], ['id'])
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'])
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint('uix_user_product_cart', 'carts', ['user_id', 'product_id'])
    op.drop_column('carts', 'personalised_member')
    op.drop_column('carts', 'personalised_size')
    op.drop_column('carts', 'personalised_message')
    op.drop_column('carts', 'personalised_date')
    op.drop_column('carts', 'personalised_name')
    # ### end Alembic commands ###
