"""Added sets

Revision ID: 5e675e6161b2
Revises: 8e9cafe2f189
Create Date: 2025-03-03 18:45:49.451355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e675e6161b2'
down_revision: Union[str, None] = '8e9cafe2f189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('primary_product_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secondary_product_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('set_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sets_pkey'),
    sa.UniqueConstraint('set_name', name='sets_set_name_key')
    )
    op.drop_table('product_sets')
    # ### end Alembic commands ###
