"""Added Foreign Key to Products Table from Carts Table

Revision ID: 70ae3c3aa977
Revises: 77f6dacaa366
Create Date: 2024-12-06 03:02:38.210193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ae3c3aa977'
down_revision: Union[str, None] = '77f6dacaa366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'carts', 'products', ['product_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    # ### end Alembic commands ###
