"""fetched from laptop

Revision ID: 755fac01e406
Revises: 
Create Date: 2025-01-14 11:31:41.894874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755fac01e406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('guest_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('total_sales', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_sales')
    op.drop_column('carts', 'guest_id')
    # ### end Alembic commands ###
