"""Weird commit

Revision ID: 7d409ea156b9
Revises: ba0b18c5d913
Create Date: 2024-10-10 18:07:26.523002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d409ea156b9'
down_revision: Union[str, None] = 'ba0b18c5d913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_product', 'carts', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_product', 'carts', type_='unique')
    # ### end Alembic commands ###
