"""Changed carts

Revision ID: 8bf310aed44e
Revises: 53e97237d32e
Create Date: 2024-11-16 13:48:25.887603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf310aed44e'
down_revision: Union[str, None] = '53e97237d32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carts_product_id_fkey', 'carts', type_='foreignkey')
    op.drop_constraint('carts_user_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'users', ['user_id'], ['id'])
    op.create_foreign_key('carts_product_id_fkey', 'carts', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
