"""made initial ratings null

Revision ID: 93a3f2b4b214
Revises: 23d3f6a78ab4
Create Date: 2024-12-21 14:34:50.993564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a3f2b4b214'
down_revision: Union[str, None] = '23d3f6a78ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
