"""Added images for trousseaus

Revision ID: a59a2db154a3
Revises: 2e07013f2b73
Create Date: 2024-10-16 17:22:03.391020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59a2db154a3'
down_revision: Union[str, None] = '2e07013f2b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('primary_image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('secondary_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'secondary_images')
    op.drop_column('products', 'primary_image')
    # ### end Alembic commands ###
