"""Added carts db

Revision ID: b7fc5bb524c3
Revises: 0a8bbd6e6726
Create Date: 2024-10-10 17:59:22.430306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fc5bb524c3'
down_revision: Union[str, None] = '0a8bbd6e6726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###
