"""Create products table

Revision ID: d21491e310e2
Revises: e76f2c4cbd4e
Create Date: 2024-10-09 13:42:18.342155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd21491e310e2'
down_revision: Union[str, None] = 'e76f2c4cbd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_gender', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trousseaus',
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('role', sa.String(), server_default='regular', nullable=True))
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('M', 'F', name='genderenum'),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'gender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('M', 'F', name='genderenum'),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_table('trousseaus')
    op.drop_table('products')
    # ### end Alembic commands ###
