"""Added guest possibility for carts

Revision ID: e0373248d728
Revises: e19f5c4038e6
Create Date: 2025-01-05 20:15:09.246183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0373248d728'
down_revision: Union[str, None] = 'e19f5c4038e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('guest_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'guest_id')
    # ### end Alembic commands ###
