"""Modified sizes

Revision ID: ea0f17902756
Revises: 1816a78ab9ac
Create Date: 2024-10-20 15:49:19.463558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0f17902756'
down_revision: Union[str, None] = '1816a78ab9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sizes', sa.JSON(), nullable=True))
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'sizes')
    # ### end Alembic commands ###
