"""Added total sales attr to products

Revision ID: f36d3346a8b2
Revises: 6fe3c99f1d74
Create Date: 2025-01-13 23:17:53.426900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36d3346a8b2'
down_revision: Union[str, None] = '6fe3c99f1d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_sales', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_sales')
    # ### end Alembic commands ###
