"""Added reviews

Revision ID: fcf179fc49f6
Revises: 5f0cde710bdf
Create Date: 2024-10-31 18:50:22.238169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf179fc49f6'
down_revision: Union[str, None] = '5f0cde710bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uix_user_product_reviews')
    )
    op.drop_constraint('uix_user_product', 'carts', type_='unique')
    op.create_unique_constraint('uix_user_product_cart', 'carts', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_product_cart', 'carts', type_='unique')
    op.create_unique_constraint('uix_user_product', 'carts', ['user_id', 'product_id'])
    op.drop_table('reviews')
    # ### end Alembic commands ###
